#!/usr/bin/env bash
#
# PHI AI Platform non-interactive installer.
#
# Expects a .env file (see .env.example) with all PHI_AI_* variables
# already populated — typically generated by installer_chatbot.py, or
# hand-written by an operator following runbooks/RUNBOOK_INSTALL.md.
#
# This script does NOT provision cloud infrastructure (buckets, KMS keys,
# IAM roles) — that's handled by Terraform in deploy/<cloud>/, which must
# be applied first. This script installs and starts the application layer
# on top of already-provisioned infrastructure.

set -euo pipefail

ENV_FILE="${1:-.env}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: env file '$ENV_FILE' not found." >&2
  echo "Run install/installer_chatbot.py first, or copy .env.example to .env and fill it in." >&2
  exit 1
fi

echo "== PHI AI Platform installer =="
echo "Using env file: $ENV_FILE"

# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

# This list must match exactly the variables core/config/settings.py's
# Settings.from_env() UNCONDITIONALLY requires (its _require() calls) -
# nothing more, nothing less. It previously checked for
# PHI_AI_FHIR_CLIENT_SECRET unconditionally, which was wrong for the
# default vendor: Epic backend services auth uses an RS384 JWT signed
# with a private key, never a client secret - see core/fhir/client.py's
# own module docstring. A real, correctly-generated .env file from this
# project's own installer would never satisfy that check, so this script
# would fail its own pre-flight validation for every Epic deployment. It
# was also simultaneously missing four variables that ARE genuinely
# required (audit bucket/key, FHIR token URL, and the private key path
# itself), so a real misconfiguration in any of those would have gone
# undetected here and surfaced later as a less clear failure inside the
# running container instead.
#
# PHI_AI_FHIR_CLIENT_SECRET now exists as a VENDOR-CONDITIONAL setting
# (required exactly when PHI_AI_EMR_VENDOR selects a profile whose
# auth_flow is oauth2_client_credentials - athenahealth as shipped; see
# core/fhir/emr_profiles.py PROFILES). It is deliberately not in this
# list: settings.py itself
# validates the combination at startup with a clearer error than this
# pre-flight could give, and duplicating conditional logic here is how
# the two drift apart.
required_vars=(
  PHI_AI_CLOUD_PROVIDER
  PHI_AI_STORAGE_BUCKET
  PHI_AI_STORAGE_REGION
  PHI_AI_KMS_KEY_ID
  PHI_AI_AUDIT_BUCKET
  PHI_AI_AUDIT_KMS_KEY_ID
  PHI_AI_FHIR_BASE_URL
  PHI_AI_FHIR_TOKEN_URL
  PHI_AI_FHIR_CLIENT_ID
  PHI_AI_FHIR_PRIVATE_KEY_PATH
)

missing=0
for var in "${required_vars[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "ERROR: required variable $var is not set in $ENV_FILE" >&2
    missing=1
  fi
done
if [[ "$missing" -eq 1 ]]; then
  exit 1
fi

echo "-- Checking prerequisites --"
command -v docker >/dev/null 2>&1 || { echo "ERROR: docker is required." >&2; exit 1; }

# FOUND AND FIXED (2026-08-17 audit, H8): `command -v docker compose`
# does NOT test whether the `docker compose` subcommand works - `command
# -v` treats each word as an independent, separately-checked command
# name (try `command -v docker nonexistent-xyz` yourself: it prints
# docker's path and exits 0, silently ignoring that the second name
# wasn't found). Since `docker` itself was already confirmed present on
# the line above, `command -v docker compose` was true unconditionally,
# regardless of whether the compose plugin was actually installed - a
# check that could never fail, and so never actually checked anything.
# The fix invokes the subcommand for real: `docker compose version`
# genuinely fails (nonzero exit, "docker: 'compose' is not a docker
# command") when the plugin is absent, and genuinely succeeds when it's
# present - a real behavioral test, not a PATH lookup on the wrong
# string. COMPOSE_CMD is captured as an array (not a single string) so
# the two-word `docker compose` invocation and the one-word legacy
# `docker-compose` fallback both expand correctly wherever it's used
# below, without relying on word-splitting a plain string.
if docker compose version >/dev/null 2>&1; then
  COMPOSE_CMD=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE_CMD=(docker-compose)
else
  echo "ERROR: docker compose is required (neither the 'docker compose' plugin nor the legacy 'docker-compose' binary was found)." >&2
  exit 1
fi

echo "-- Verifying cloud credentials are reachable --"
case "$PHI_AI_CLOUD_PROVIDER" in
  aws)
    command -v aws >/dev/null 2>&1 && aws sts get-caller-identity >/dev/null \
      && echo "AWS credentials OK" || echo "WARNING: could not verify AWS credentials; continuing."
    ;;
  gcp)
    command -v gcloud >/dev/null 2>&1 && gcloud auth list --filter=status:ACTIVE --format="value(account)" \
      && echo "GCP credentials OK" || echo "WARNING: could not verify GCP credentials; continuing."
    ;;
  azure)
    command -v az >/dev/null 2>&1 && az account show >/dev/null \
      && echo "Azure credentials OK" || echo "WARNING: could not verify Azure credentials; continuing."
    ;;
  *)
    echo "ERROR: unknown PHI_AI_CLOUD_PROVIDER: $PHI_AI_CLOUD_PROVIDER" >&2
    exit 1
    ;;
esac

echo "-- Pulling/building images --"
"${COMPOSE_CMD[@]}" --env-file "$ENV_FILE" pull || true
"${COMPOSE_CMD[@]}" --env-file "$ENV_FILE" build

echo "-- Starting services --"
# FOUND AND FIXED (2026-08-17 audit, H8): this previously ran a bare
# `docker compose up -d`, which starts every service in
# docker-compose.yml unconditionally - including `bulk-scheduler`, which
# runbooks/RUNBOOK_AWS_SETUP.md's own Step 11 explicitly warns will
# "exit immediately with 'PHI_AI_FHIR_GROUP_ID is not set' and then
# restart in a loop (restart: unless-stopped)" if that variable isn't
# set - Step 11 tells a HUMAN to run `docker compose up -d app scheduler`
# instead in that case, but this script, the NON-interactive installer
# meant to automate exactly that judgment call, never implemented the
# check the runbook already knew was necessary. Every install run
# without Bulk Data Export configured (the common case - see Step 6b,
# "optional") produced an immediate, permanent restart-crash-loop on one
# of its three containers from the very first run. Fixed by checking the
# same variable the runbook's human instructions check, automating
# exactly the judgment call Step 11 already documents rather than
# leaving it as a manual override only a reader of that specific runbook
# section would know to apply.
if [[ -n "${PHI_AI_FHIR_GROUP_ID:-}" ]]; then
  "${COMPOSE_CMD[@]}" --env-file "$ENV_FILE" up -d
else
  echo "PHI_AI_FHIR_GROUP_ID is not set - starting app and scheduler only, not bulk-scheduler."
  echo "(bulk-scheduler would exit immediately and restart-loop without a Group ID - see"
  echo " runbooks/RUNBOOK_AWS_SETUP.md Step 6b/11. Set PHI_AI_FHIR_GROUP_ID and re-run"
  echo " this script, or run '${COMPOSE_CMD[*]} up -d bulk-scheduler' yourself, once you have one.)"
  "${COMPOSE_CMD[@]}" --env-file "$ENV_FILE" up -d app scheduler
fi

echo ""
echo "== Install complete =="
echo "Next steps:"
echo "  1. Review runbooks/RUNBOOK_INSTALL.md 'Post-install verification' section."
echo "  2. Run a test ingestion cycle against a non-production FHIR sandbox first."
echo "  3. Confirm audit log chain integrity: ${COMPOSE_CMD[*]} exec app python -m core.audit.verify"
# Made by Ryan Gomez & Co. Inc.
