#!/usr/bin/env python3
# Copyright 2026 Ryan Gomez & Co. Inc. — PHI AI
# Licensed under the Apache License, Version 2.0 (see LICENSE); attribution notices must be retained (see NOTICE).
"""
Load the local Layer-2 synthetic corpus (testdata/layer2, generated by
scripts/generate_corpus.py) into a live deployment through the REAL
ingestion pipeline - the same FHIRIngestionClient.store_resource() path
the schedulers use: envelope encryption, S3 write, tamper-evident audit
record, Postgres index entry, OMOP ETL row. Nothing is short-cut; the
only difference from core/fhir/scheduler.py is where resources come
from (local Synthea bundles rather than a vendor FHIR API), so no EMR
authentication happens.

    python scripts/load_local_corpus.py [--bundles N] [--skip-types Observation,...]

SYNTHETIC DATA ONLY. Every resource in testdata/layer2 carries the
HTEST marker written by generate_corpus.py; this script refuses any
resource without it, so it cannot be repurposed to bulk-load real PHI
around the EMR connectors.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from core.audit.log import AuditLog  # noqa: E402
from core.config.scale_profile import profile_from_env  # noqa: E402
from core.config.settings import Settings  # noqa: E402
from core.crypto.envelope import EnvelopeEncryptor  # noqa: E402
from core.db import connection as db_connection  # noqa: E402
from core.db import index as db_index  # noqa: E402
from core.db import omop_etl  # noqa: E402
from core.fhir.client import FHIRIngestionClient  # noqa: E402
from core.fhir.emr_profiles import profile_for  # noqa: E402
from core.storage.factory import build_audit_sink, build_kms, build_storage  # noqa: E402

CORPUS = REPO_ROOT / "testdata" / "layer2"


def _is_htest(resource: dict) -> bool:
    for tag in (resource.get("meta") or {}).get("tag") or []:
        if tag.get("code") == "HTEST":
            return True
    return False


def _normalise_references(bundle: dict) -> None:
    """Rewrite intra-bundle `urn:uuid:` references to `Type/id` form.

    Synthea emits transaction bundles whose entries reference each other
    by fullUrl (`urn:uuid:<id>`); a FHIR server resolves those to
    resource ids on ingest. This loader stands in for that server, so it
    performs the same resolution — without it every subject/encounter
    reference is a URN the index and the OMOP ETL rightly cannot read,
    and every stored resource ends up patient-less.
    """
    urn_map: dict[str, str] = {}
    for entry in bundle.get("entry", []):
        full = entry.get("fullUrl") or ""
        res = entry.get("resource") or {}
        if full.startswith("urn:uuid:") and res.get("resourceType") and res.get("id"):
            urn_map[full] = f"{res['resourceType']}/{res['id']}"

    def walk(node) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "reference" and isinstance(value, str) and value in urn_map:
                    node[key] = urn_map[value]
                else:
                    walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    walk(bundle)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bundles", type=int, default=0,
                        help="load only N bundles from --offset (0 = all)")
    parser.add_argument("--offset", type=int, default=0,
                        help="skip this many bundles first — lets several loader "
                             "processes shard the corpus. Safe to run in parallel: "
                             "bundles are per-patient so storage keys are disjoint, "
                             "and the audit chain records concurrent writers as "
                             "forks by design (core/audit/log.py)")
    parser.add_argument("--skip-types", default="",
                        help="comma-separated resourceTypes to skip")
    args = parser.parse_args()
    skip = {t.strip() for t in args.skip_types.split(",") if t.strip()}

    settings = Settings.from_env()
    storage = build_storage(settings)
    encryptor = EnvelopeEncryptor(kms=build_kms(settings))
    sink = build_audit_sink(settings)
    audit = AuditLog(sink=sink, last_known_hash=sink.last_hash())
    profile = profile_for(settings.emr_vendor)
    supported = set(profile.supported_resources)

    db_conn = None
    if settings.db_target_configured() and settings.db_ingest_username:
        db_conn = db_connection.connect(settings, username=settings.db_ingest_username)
        print("connected: Postgres index")
    omop_conn = None
    if settings.omop_target_configured():
        omop_conn = db_connection.connect(settings, username=settings.omop_etl_username)
        print("connected: OMOP analytics layer")

    def index_writer(result, resource: dict) -> None:
        if db_conn is None:
            return
        db_index.write_index_entry(db_conn, db_index.IndexEntry(
            resource_type=result.resource_type,
            resource_id=result.resource_id,
            storage_key=result.storage_key,
            storage_version_id=result.version_id,
            sha256_hex=result.sha256_hex,
            patient_reference=db_index.extract_patient_reference(resource),
            retention_until=result.retention_until,
        ))

    def omop_writer(result, resource: dict) -> None:
        if omop_conn is None:
            return
        omop_etl.etl_resource(omop_conn, resource, result.storage_key)

    client = FHIRIngestionClient(
        base_url=settings.fhir_base_url,
        profile=profile,
        storage=storage,
        encryptor=encryptor,
        audit=audit,
        retention_years=settings.retention_years,
        retention_years_overrides=settings.retention_years_overrides,
        actor="phi-ai-local-corpus-loader",
        index_writer=index_writer if db_conn is not None else None,
        omop_writer=omop_writer if omop_conn is not None else None,
        profile_config=profile_from_env(),
    )

    bundles = sorted(p for p in CORPUS.glob("*.json") if p.name != "MANIFEST.json")
    bundles = bundles[args.offset:]
    if args.bundles:
        bundles = bundles[: args.bundles]
    if not bundles:
        print(f"no bundles found in {CORPUS} - run scripts/generate_corpus.py first")
        return 1

    started = time.time()
    stored = skipped = refused = 0
    for i, path in enumerate(bundles, 1):
        bundle = json.loads(path.read_text())
        _normalise_references(bundle)
        for entry in bundle.get("entry", []):
            resource = entry.get("resource") or {}
            rtype = resource.get("resourceType")
            if rtype not in supported or rtype in skip:
                skipped += 1
                continue
            if not _is_htest(resource):
                refused += 1
                continue
            client.store_resource(resource)
            stored += 1
        rate = stored / max(time.time() - started, 1e-9)
        print(f"[{i}/{len(bundles)}] {path.name[:40]:40s} stored={stored} "
              f"skipped={skipped} rate={rate:.1f}/s", flush=True)

    if db_conn is not None:
        db_conn.close()
    if omop_conn is not None:
        omop_conn.close()
    print(f"done: {stored} stored, {skipped} unsupported-type, "
          f"{refused} refused (no HTEST marker), {time.time() - started:.0f}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
# Made by Ryan Gomez & Co. Inc.
