# ---------------------------------------------------------------------------
# Azure Database for PostgreSQL Flexible Server: the Azure equivalent of
# deploy/aws/rds.tf's RDS instance and deploy/gcp/database.tf's Cloud
# SQL instance. Backs BOTH the lightweight stored-resource index
# (core/db/schema.sql) and, once core/db/omop_bootstrap_azure.sql is
# run, the OMOP CDM analytics layer (core/db/omop_schema.sql).
#
# See core/db/connection.py's _connect_azure() docstring for the
# application-side mechanism this enables: a Microsoft Entra access
# token scoped to https://ossrdbms-aad.database.windows.net, presented
# as the password to a standard psycopg connection - structurally the
# closest of the three clouds to AWS's own approach.
#
# UNLIKE GCP (see deploy/gcp/database.tf's own header for the full
# account of why Cloud SQL's IAM model collapses index/OMOP role
# separation into one identity), Azure's pgaadauth_create_principal_with_oid()
# lets a Postgres role name be chosen freely, independent of the
# authenticating identity's own name - so the SAME managed identity
# (identities.tf's ingest) CAN be registered under two different role
# names (phi_ai_ingest via core/db/bootstrap_azure.sql, omop_etl
# via core/db/omop_bootstrap_azure.sql), preserving genuine role
# separation the same way AWS does. core/db/omop_bootstrap_azure.sql
# creates omop_etl as its own distinct role, unlike its GCP sibling.
#
# password_auth_enabled = true is DELIBERATE, not an oversight, even
# though this project's own principle is "no password, ever" for every
# application-facing credential. A real, documented Azure provider
# gotcha (confirmed via a live upstream GitHub issue found during this
# stack's own research): setting password_auth_enabled = false from
# server creation, before any Microsoft Entra administrator has
# connected and created a database, can result in the server's default
# database being owned by an inaccessible "azuresu" role with no
# working path to grant permissions on it - a real lockout risk, not a
# theoretical one. This stack accepts a master password
# (random_password.db_master below) for exactly the same narrow purpose
# AWS's own RDS master password serves: a one-time bootstrap credential,
# generated by Terraform, used once by an operator to run
# core/db/bootstrap_azure.sql and core/db/omop_bootstrap_azure.sql, never
# touched by the running application (core/db/connection.py's
# _connect_azure() only ever presents an Entra token, never this
# password). See runbooks/RUNBOOK_AZURE_SETUP.md for the exact
# retrieval command, mirroring RUNBOOK_AWS_SETUP.md's Step 6a.
#
# Gated on var.enable_db, matching deploy/aws/rds.tf and
# deploy/gcp/database.tf's identical optionality.
# ---------------------------------------------------------------------------

resource "random_password" "db_master" {
  count = var.enable_db ? 1 : 0

  length  = 32
  special = true
  # Flexible Server rejects a handful of characters in the admin
  # password (confirmed against Microsoft's own documented restricted
  # character set for this field); excluding the full override_special
  # set here and relying on random_password's own default safe special
  # characters avoids relying on an unverified narrower list.
}

resource "azurerm_postgresql_flexible_server" "index" {
  count = var.enable_db ? 1 : 0

  name                = "${var.name_prefix}-index"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  version             = "16"

  # A Postgres ROLE name, and ForceNew in the azurerm provider: Flexible
  # Server's API cannot rename an administrator in place, so changing
  # this after the first apply plans DESTROY + CREATE of the whole
  # server. Choose it before applying.
  #
  # Deliberately NOT guarded with `ignore_changes`. Suppressing the diff
  # would also permanently blind Terraform to drift on the one attribute
  # the entire Entra bootstrap path depends on, and a silent mismatch
  # there is an outage rather than a cosmetic diff. deploy/aws/rds.tf
  # makes the same call for the same reason.
  #
  # This is the one-time bootstrap credential an operator connects as to
  # run core/db/bootstrap_azure.sql and core/db/omop_bootstrap_azure.sql
  # (see this file's header), so it must match what those runbook steps
  # say to connect as.
  administrator_login    = "phi_ai_master"
  administrator_password = random_password.db_master[0].result

  # 32768 MB (32 GB) is the documented minimum for Flexible Server -
  # stated explicitly here rather than left to the provider's own
  # default, the same discipline this project applies to every other
  # default across all three clouds.
  storage_mb = var.db_storage_mb

  # Cheapest tier confirmed during this stack's own research
  # (Burstable B1ms, ~$12-15/month) - genuinely NOT free; see the cost
  # note at the bottom of this file. B-series (Burstable) does not
  # support high_availability - left unset here, matching this whole
  # stack's single-zone, free/near-free posture on every other
  # resource.
  sku_name = var.db_sku_name

  zone = "1"

  # See this file's own header for why password_auth_enabled stays
  # true. active_directory_auth_enabled = true is what makes
  # core/db/connection.py's _connect_azure() possible at all.
  authentication {
    active_directory_auth_enabled = true
    password_auth_enabled         = true
    tenant_id                     = data.azurerm_client_config.current.tenant_id
  }

  backup_retention_days = 7

  public_network_access_enabled = var.db_publicly_accessible

  lifecycle {
    precondition {
      condition     = !var.enable_db || (var.db_aad_admin_object_id != "" && var.db_aad_admin_principal_name != "")
      error_message = "db_aad_admin_object_id and db_aad_admin_principal_name must both be set when enable_db is true - there is no sensible default administrator identity. See this variable's own description for how to obtain your own object ID and principal name."
    }
  }
}

resource "azurerm_postgresql_flexible_server_database" "index" {
  count = var.enable_db ? 1 : 0

  # A Postgres DATABASE name, matching deploy/aws/rds.tf's db_name and
  # deploy/gcp/database.tf's google_sql_database.index. Both bootstrap
  # scripts connect to it by name, and outputs.tf's env_fragment emits
  # PHI_AI_DB_NAME from this resource's own attribute rather than
  # repeating the literal, so the fragment cannot drift from what is
  # actually created here.
  name      = "phi_ai_index"
  server_id = azurerm_postgresql_flexible_server.index[0].id
  collation = "en_US.utf8"
  charset   = "UTF8"
}

# ---------------------------------------------------------------------------
# Microsoft Entra administrator - the identity that can FIRST connect
# and run core/db/bootstrap_azure.sql/core/db/omop_bootstrap_azure.sql,
# which in turn register the ingest/restore managed identities as their
# own, distinctly-named Postgres roles via pgaadauth_create_principal_with_oid().
# Typically the deploying operator's own Azure AD identity - there is no
# sensible default this stack can compute on its own (unlike
# data.azurerm_client_config.current.object_id, which is the identity
# TERRAFORM is running as, not necessarily who should administer the
# database afterward) - see var.db_aad_admin_object_id's own
# description for the exact az CLI commands to obtain both required
# values.
# ---------------------------------------------------------------------------

resource "azurerm_postgresql_flexible_server_active_directory_administrator" "main" {
  count = var.enable_db ? 1 : 0

  server_name         = azurerm_postgresql_flexible_server.index[0].name
  resource_group_name = azurerm_resource_group.main.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  object_id           = var.db_aad_admin_object_id
  principal_name      = var.db_aad_admin_principal_name
  principal_type      = var.db_aad_admin_principal_type
}

# ---------------------------------------------------------------------------
# Firewall rules - only meaningful when public_network_access_enabled is
# true. Flexible Server's firewall rule resource takes a start/end IP
# range rather than CIDR notation directly; each entry in
# var.db_allowed_ip_addresses becomes a single-address range
# (start == end), matching the common "allow my own laptop" case this
# project's AWS/GCP equivalents (db_allowed_cidr_blocks, as /32 entries)
# are also scoped to in practice, without needing CIDR-range parsing
# logic for the general case this stack does not otherwise require.
# ---------------------------------------------------------------------------

resource "azurerm_postgresql_flexible_server_firewall_rule" "allowed" {
  for_each = var.enable_db ? { for idx, ip in var.db_allowed_ip_addresses : tostring(idx) => ip } : {}

  name             = "allowed-${each.key}"
  server_id        = azurerm_postgresql_flexible_server.index[0].id
  start_ip_address = each.value
  end_ip_address   = each.value
}

# ---------------------------------------------------------------------------
# On cost: what's actually confirmed here, stated plainly
#
# UNLIKE this stack's storage and Key Vault costs (see storage.tf's own
# "On redundancy" section), Flexible Server has NO free tier of any
# kind - not even the time-limited new-account credit GCP's Cloud SQL
# offers. Confirmed during this stack's own research: Burstable B1ms,
# the cheapest available tier, runs roughly $12-15/month for compute
# alone, plus separate storage billing (~$0.115/GB) - genuinely the
# most expensive of the three clouds' cheapest-tier database options
# researched for this project (AWS's free-tier-eligible db.t4g.micro
# during its first 12 months, then GCP's ~$7-10/month db-f1-micro, then
# this). Budget for this explicitly rather than assuming it fits
# alongside the rest of this stack's free/near-free posture.
# ---------------------------------------------------------------------------
# Made by Ryan Gomez & Co. Inc.
